### ISSUE TITLE
more than one image 

### ISSUE THREAD

**Issue by rcan7412** [Gix075/brainImageLink#1]
Hi,

Is it possible to manage more than one image with the brainImageLink module ?

Regards.

Rod

**Comment by Gix075** [comment]
Hi,
not with the same module, you need to load one module for each image.

**Comment by rcan7412** [comment]
thanks

De : Gix075 [mailto:notifications@github.com] 
Envoyé : mardi 22 décembre 2015 12:15
À : Gix075/brainImageLink brainImageLink@noreply.github.com
Cc : rcan7412 rcan7412@gmail.com
Objet : Re: [brainImageLink] more than one image (#1)

Hi,
not with the same module, you need to load one module for each image.
